<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427061609 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_user ADD google_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ALTER password DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E976F5C865 ON app_user (google_id)');
        $this->addSql('ALTER TABLE job_application ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE job_application ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_3e8af7dda76ed395 RENAME TO IDX_C737C688A76ED395');
        $this->addSql('ALTER INDEX idx_3e8af7ddc58d3b1e RENAME TO IDX_C737C6883481D195');
        $this->addSql('DROP INDEX idx_job_offer_published_at');
        $this->addSql('DROP INDEX uniq_job_offer_source_external');
        $this->addSql('ALTER TABLE job_offer ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE job_offer ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_88BDF3E976F5C865');
        $this->addSql('ALTER TABLE app_user DROP google_id');
        $this->addSql('ALTER TABLE app_user ALTER password SET NOT NULL');
        $this->addSql('ALTER TABLE job_application ALTER id SET DEFAULT nextval(\'job_application_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE job_application ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_c737c6883481d195 RENAME TO idx_3e8af7ddc58d3b1e');
        $this->addSql('ALTER INDEX idx_c737c688a76ed395 RENAME TO idx_3e8af7dda76ed395');
        $this->addSql('ALTER TABLE job_offer ALTER id SET DEFAULT nextval(\'job_offer_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE job_offer ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_job_offer_published_at ON job_offer (published_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_offer_source_external ON job_offer (source, external_id)');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0');
        $this->addSql('DROP INDEX IDX_75EA56E0E3BD61CE');
        $this->addSql('DROP INDEX IDX_75EA56E016BA31DB');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }
}
